micronaut:
  application:
    name: pixKeymanagerRest
  server:
    port: ${SERVER_PORT:8081}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManagerGrpc:
      address: 'localhost:50051'